# Generated by Django 6.0 on 2025-12-08 03:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=100, verbose_name='Nombre Empresa')),
                ('contacto', models.CharField(max_length=100, verbose_name='Nombre Contacto')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
            ],
        ),
        migrations.AlterField(
            model_name='pedido',
            name='direccion_envio',
            field=models.TextField(verbose_name='Dirección de Envío'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de Pago'), ('pagado', 'Pagado'), ('enviado', 'Enviado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(default='tarjeta', max_length=50, verbose_name='Método de Pago'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='direccion',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección de Envío'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/', verbose_name='Foto de Perfil'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='resena',
            name='calificacion',
            field=models.IntegerField(choices=[(1, '⭐'), (2, '⭐⭐'), (3, '⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (5, '⭐⭐⭐⭐⭐')], verbose_name='Calificación'),
        ),
        migrations.AlterField(
            model_name='resena',
            name='comentario',
            field=models.TextField(verbose_name='Tu opinión'),
        ),
        migrations.AddField(
            model_name='libro',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tienda.proveedor', verbose_name='Proveedor'),
        ),
    ]
